name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Move built files
        run: |
          mv docs/build/html docs/build/public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/public
